version: '3.9'
services:
  oscar:
    image: rogerrum/docker-oscar:0.0.2
    ports:
      - 80:8080
    volumes:
      - type: volume
        source: rawdata
        target: /data
      - type: bind
        source: ${SD_CARD_PATH}
        target: /airsense
        read_only: true
volumes:
  rawdata:
